### ISSUE TITLE
프레임 수 조정

### ISSUE THREAD

**Issue by SongSukhwan** [essems/REDFramework-iOS#1]
지금 현재 NVR 16채널에서 16채널 전체를 요청하는데 채널 하나당 12프레임정도 들어옵니다. 
채널 하나당 30프레임이 들어올수 있도록 설정하는 법이 궁금합니다.

**Comment by essems** [comment]
감시인가요? 검색인가요?
NVR 감시 중  FrameRate를 조절하는 프로토콜은 없습니다. 
NVR과 모바일 사이의 네트워크 대역폭, 모바일 성능이 충분하다면 30 프레임을 모두 수신할 수 있지만, 
그렇지 못할 경우는 NVR에서 30프레임 수신이 불가능합니다.
