### ISSUE TITLE
iOS 펌웨어 업그레이드 취소 후 라이브 접속 문제

### ISSUE THREAD

**Issue by SongSukhwan** [essems/REDFramework-iOS#2]
펌웨어 업그레이드 도중 업그레이드 중지 후 라이브 접속이 되지 않습니다.

루틴은 
requestDeviceUpgradeCancel()->onReceiveRemoteUpgradeDeviceCancel->disconnect()->onDisconnected 
이후에 라이브 재접속
_watcher -> connect 하고나면 onDisconnected:에 (27 : SSL connection failed) 이 값이 오고 접속이 되질 않습니다.

원인이 무엇이고 해결책은 어떻게 해야하는지 알려주시기 바랍니다.

**Comment by essems** [comment]
211.196.55.246:8018 장비에 접속해봤지만...
현재 업그레이드 서비스 불가라고 뜨는데요.. .
혹시나 위 장비 말고 다른 테스트 장비가 있으면 알려주세요.

**Comment by SongSukhwan** [comment]
ip : 211.196.55.246 port : 8999 하나 더 있습니다. 
그리고 위 주소 장비와 지금 장비 둘다 접속 됩니다. 아까 테스트 할때 접속하셨던것 같습니다..;;

**Comment by SongSukhwan** [comment]
REDCore를 여러번 생성해서 발생한 문제였던것 같습니다. Appdelegate쪽에서 한번만 초기화 해주니까 위 문제가 발생하지 않았습니다.

**Comment by essems** [comment]
문제가 해결된 것으로 판단하고 이 이슈는 Close하겠습니다.
